export const categories = {
  BIOCHIMIE: "BIOCHIMIE",
  PARASITOLOGIE: "PARASITOLOGIE",
  SEROLOGIE_IMMUNOLOGIE: "SEROLOGIE - IMMUNOLOGIE",
  HEMATOLOGIE: "HEMATOLOGIE",
  HEMOSTASE: "HEMOSTASE",
  HORMONES: "HORMONES",
  IMMUNOPHENOTYPAGE: "IMMUNOPHENOTYPAGE",
  IMMUNOHEMATOLOGIE: "Immuno-Hematologie",
  ENZYMOLOGIE: "ENZYMOLOGIE",
};
