export const paperTypes = {
  SINGLE: "SINGLE",
  DOUBLE_REF_TEST: "DOUBLE_REF_TEST",
  DOUBLE_UNIT_TEST: "DOUBLE_UNIT_TEST",
  GROUP_TEST: "GROUP_TEST",
  MULTIPLE_REF_TEST: "MULTIPLE_REF_TEST",
  WIDAL_TEST: "WIDAL_TEST",
  MULTIPLE_PARAM: "MULTIPLE_PARA",
};
