const PATIENT_ACTION_TYPES = {
  ADD_PATIENT: "ADD_PATIENT",
  ADD_PATIENT_TEST_EXAM: "ADD_PATIENT_TEST_EXAM",

  UPDATE_PATIENT_INFO: "UPDATE_PATIENT_INFO",
  UPDATE_PATIENT_DOCTOR_INFO: "UPDATE_PATIENT_DOCTOR_INFO",
  UPDATE_PATIENT_RESULT: "UPDATE_PATIENT_RESULT",
  SET_SELECTED_PATIENT_ID: "SET_SELECTED_PATIENT_ID",

  DELETE_PATIENT: "DELETE_PATIENT",
  DELETE_PATIENT_TEST_EXAM: "DELETE_PATIENT_TEST_EXAM",

  ADD_PATIENT_DOCTOR_NB: "ADD_PATIENT_DOCTOR_NB",
  UPDATE_PATIENT_DOCTOR_NB: "UPDATE_PATIENT_DOCTOR_NB",
  DELETE_PATIENT_DOCTOR_NB: "DELETE_PATIENT_DOCTOR_NB",

  ADD_PATIENT_TO_HISTORY: "ADD_PATIENT_TO_HISTORY",

  RESET_CURRENT_PATIENTS: "RESET_CURRENT_PATIENTS",

  DELETE_PATIENT_FROM_HISTORY: "DELETE_PATIENT_FROM_HISTORY",
};

export default PATIENT_ACTION_TYPES;
