const PATIENT_ACTION_TYPES = {
  ADD_PATIENT: "ADD_PATIENT",
  ADD_PATIENT_TEST_EXAM: "ADD_PATIENT_TEST_EXAM",

  UPDATE_PATIENT_INFO: "UPDATE_PATIENT_INFO",
  UPDATE_PATIENT_DOCTOR_INFO: "UPDATE_PATIENT_DOCTOR_INFO",
  UPDATE_PATIENT_RESULT: "UPDATE_PATIENT_RESULT",
  SET_SELECTED_PATIENT_ID: "SET_SELECTED_PATIENT_ID",

  DELETE_PATIENT: "DELETE_PATIENT",
  DELETE_PATIENT_TEST_EXAM: "DELETE_PATIENT_TEST_EXAM",
};

export default PATIENT_ACTION_TYPES;
